---
- name: restart apache
  service:
    name: apache2
    state: restarted
  sudo: yes

- name: start apache
  service:
    name: apache2
    start: started
  sudo: yes

- name: reload apache
  service:
    name: apache2
    state: reloaded
  sudo: yes
