---
- hosts: localhost
  vars:
    mysql_users:
      - { name: vagrant, password: vagrant }
  roles:
    - git/debian
    - base/debian
    - vim/debian
    - { role: vagrant/debian, plugins: ['vagrant-hostmanager'] }
    - oh-my-zsh/debian
    - ruby/debian
    - nodejs/debian
    - php/debian
    - twig/debian
    - composer/debian
    - pear/debian
    - php_cs/debian
    - phpunit/debian
    - apache/debian
    - mysql/debian
    - phpmyadmin/debian
